/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class string_calculator {
    public int add(String input) {
    	if(input.equals("")) {
    		return 0;
    	} else if(input.length() == 1) {
    		return Integer.parseInt(input);
    	}
        return 0;
    }
}
